### ISSUE TITLE
Add resource pool option

### ISSUE THREAD

**Issue by sitle** [snobear/ezmomi#12]
It would be great if we can choose where the template must be clone (in what ressource pool and what datastore or directory) via the command line.

**Comment by derchrisuk** [comment]
Yes, that would be helpful.
At the moment the newly created/cloned VM is being created at the root of the VM inventory.
 would like to see an option where I can select a Folder where this VM has to go to.

**Comment by snobear** [comment]
@derchrisuk @sitle I am going to be implementing this real soon.  We just did some housekeeping and put everything into nice neat folders so I also need this functionality.

**Comment by derchrisuk** [comment]
Thanks,

I already tried to implement it myself, but not sure how to convert the str given as an option on the CLI to a vim.Folder object.
Or get some other error that the object has already been deleted.

**Comment by derchrisuk** [comment]
Ok, after some trial and error I got the directory option running.
It is not pretty, so not sure if I should make a PR out of it.

**Comment by snobear** [comment]
Almost there, but for some reason `WaitForTasks` is hanging and never completing regardless of outcome.  We've recently upgraded vcenter to 6.0 so perhaps there is an API change.  Need to investigate.

**Comment by snobear** [comment]
@derchrisuk @sitle can you checkout the `resourcepool` branch and test it against your environment?  I'm wondering if it is a vcenter 5 vs 6 thing.  Assuming someone has a 5.x to test against.

**Comment by snobear** [comment]
Nevermind, I fixed `WaitForTasks`, using pvmomi community samples as a guide.

I changed this issue to only refer to resource pools.  If someone wants an option to specify folder and/or datastore, go ahead and open a separate issue.

**Comment by snobear** [comment]
ezmomi has been updated in pypi to 0.4.1.  You can upgrade with:

```
pip install -U ezmomi
```
