### ISSUE TITLE
Changing IP on existing adapter

### ISSUE THREAD

**Issue by alans09** [snobear/ezmomi#25]
I have virtual machine that I need to clone and change network settings.
So I defined it's name and networks. It looks that this is working but.

After clone It just create new adapter with settings. This adapter is even not connected to network (network label). Network connections are empty.

Issue a) 
    It is possible to connect adapter to some known network/virtual switch

Issue b)
    Is there any way how to clone virtual machine and:
    1) remove all network adapters and get new one that is connected to specified network (eg. dummy     network)
    2) edit adapter that exists and change just ip address?

Maybe the 1) feature will be the best but I hope there is possibility for 2 also.

**Comment by snobear** [comment]
Fixed in #27.
