### ISSUE TITLE
Possible problem using distributed switches

### ISSUE THREAD

**Issue by rostchri** [snobear/ezmomi#28]
ezmomi list --type Network returns the following Object in my setup:
dvportport-98  VLAN_1909

I want to use that, so i defined:
networks:
  '192.168.0.0/24'
      ...
      network: 'VLAN_1909'

After cloning a vm using ezmomi given a ip in network 192.168.0.0, the virtual-machine's 
network-interface is disconnected and ezmomi list --type Network returns now
network-6626 VLAN_1909
dvportport-98  VLAN_1909

That is not the way it should work ...
How to specify the vlan-name at the distributed switch, without creating new bogus vlans
while cloning?

**Comment by snobear** [comment]
@rostchri Interesting. Speaking in vSphere API terms, it looks like there is a different "managed object type" for [DistributedVirtualPortgroup](http://pubs.vmware.com/vsphere-50/index.jsp#com.vmware.wssdk.apiref.doc_50/vim.dvs.DistributedVirtualPortgroup.html).  
```
ezmomi list --type DistributedVirtualPortgroup
```
It's an extension/subclass of `network`, so that explains why it shows up in the list for `ezmomi list --type Network`. Offhand, I think the solution would be to allow for a `distributedvirtualportgroup:` setting in the ezmomi networks config. It would place the NIC in the DVPG if it was set. If both `distributedvirtualportgroup:` and `network:` were set, it would choose `distributedvirtualportgroup:` first for the NIC as a priority.  I think that makes sense since its more specific per vSphere docs.  I'm not that familiar with DVPGs.  Does that solution make sense to you?

**Comment by rostchri** [comment]
Yes that makes sense.

**Comment by daniloharuo** [comment]
+1

Same issue here!

**Comment by rostchri** [comment]
Following modifications to ezmomi.py in ezmomi-0.3.1
are usable with distributed switches. I'm sure the author can write a 
clean fix (usable for environments with and without distributed switches) based
on this modifications. 


227             # 4000 seems to be the value to use for a vmxnet3 device
228             nic.device.key = 4000
229             nic.device.deviceInfo = vim.Description()
230             nic.device.deviceInfo.label = 'Network Adapter %s' % (key + 1)
231             nic.device.deviceInfo.summary = ip_settings[key]['network']
232             # find a DistributedVirtualPortgroup with that name
233             pg_obj                              = self.get_obj([vim.dvs.DistributedVirtualPortgroup],ip_settings[key]['network'])
234             dvs_port_connection                 = vim.dvs.PortConnection()
235             dvs_port_connection.portgroupKey    = pg_obj.key
236             dvs_port_connection.switchUuid      = pg_obj.config.distributedVirtualSwitch.uuid
237             #print dvs_port_connection
238             nic.device.backing                  = vim.vm.device.VirtualEthernetCard.DistributedVirtualPortBackingInfo()
239             nic.device.backing.port             = dvs_port_connection
240             # else: use traditional network-setup without distributed switches
241             #nic.device.backing = (
242             #    vim.vm.device.VirtualEthernetCard.NetworkBackingInfo()
243             #)
244             #nic.device.backing.network = (
245             #    self.get_obj([vim.Network], ip_settings[key]['network'])
246             #)
247             #nic.device.backing.deviceName = ip_settings[key]['network']
248             #nic.device.backing.useAutoDetect = False
249             nic.device.connectable = vim.vm.device.VirtualDevice.ConnectInfo()
250             nic.device.connectable.startConnected = True
251             nic.device.connectable.allowGuestControl = True
252             devices.append(nic)

**Comment by snobear** [comment]
Thanks Christian, that code will be helpful. Will try to incorporate it
soon.

**Comment by daniloharuo** [comment]
Thanks Christian! @rostchri

**Comment by snobear** [comment]
Reopening as it needs to be added to ezmomi codebase.

**Comment by snobear** [comment]
@rostchri  @daniloharuo Can you all pull down PR #72 and give it a test to see if the distributed virtual port group works as expected?  Then I can merge it.

**Comment by snobear** [comment]
Distributed virtual port group support has been added. Its currently in the master branch...will release an updated py package soon.
