### ISSUE TITLE
Bad merge resolution resulted in "powerOn" behavior which actually destroys VMs 

### ISSUE THREAD

**Issue by bsherman** [snobear/ezmomi#38]
Sad panda :(

Looks like there was a merge conflict on ezmomi.py here: 5491a54a59efe0636ab3defa81673df83c513b46
The proper conflict resolution would have been to remove the whole chunk... Oops.

Instead b2a58c316ff4250d3da135370370f1024fbf48aa left dangerous code in place.

I'll be fixing immediately.

**Comment by bsherman** [comment]
@snobear the fix for this is committed to both develop and master, including a version bump to 0.3.1 ... just needs a release here and for pypi to be updated. I'm not sure what that process looks like even if I did/do have access. Pretty brutal bug though, hence my certainty that we want a release.

**Comment by snobear** [comment]
Yikes! I'll pull this down and get it into pypi asap.

**Comment by snobear** [comment]
0.3.1 is up in pypi: https://pypi.python.org/pypi/ezmomi

Anyone with 0.3.0 should update:

```
pip install ezmomi --upgrade
```

Thanks @bsherman!

**Comment by bsherman** [comment]
Thank you for jumping on it ASAP!
