### ISSUE TITLE
Disable Self Signed Certificate Verification?

### ISSUE THREAD

**Issue by aes512** [snobear/ezmomi#46]
Any thoughts? Trying to get this tool to work with vCenter 5.5..

```
ezmomi list --type HostSystem
Unable to connect to vsphere server.
[Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by aes512** [comment]
Should have mentioned that this was on an OSX (10.10.4) client, this problem doesn't seem to exist on Linux.

I see that work is being done in https://github.com/vmware/pyvmomi so I'll close this

**Comment by murarisumit** [comment]
@aes512, is this working now. I'm facing this issue.

**Comment by murarisumit** [comment]
@snobear, I'm getting this error. 

When trying pyvmomi, there was work around in samples to use it via setting 
`
context.verify_mode = ssl.CERT_NONE`

Is there any specific reason of not doing, just asking here. If needed I can do that with flag like --no_ssl_verify.

**Comment by snobear** [comment]
Hi @murarisumit, I want to avoid hardcoding that ssl context as it is a bad practice security-wise. But I like the idea of adding an optional `--no-ssl-verify` flag that allows the user to set it.  Could you make a PR to add that?

**Comment by murarisumit** [comment]
sure, assign it to me 👍

**Comment by murarisumit** [comment]
it's already sorted out in urllib3, it's works without flag too.

**Comment by snobear** [comment]
@murarisumit correct, it still works but throws a warning. If you can fork, fix, and make a pull request for that param I'll take a look and merge it in.

**Comment by murarisumit** [comment]
Hey @snobear, sent pull request for it: https://github.com/snobear/ezmomi/pull/79

**Comment by murarisumit** [comment]
@snobear I think we can close this ticket now.
