### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by pathcl** [snobear/ezmomi#53]
Hello,

I've just installed ezmomi and noticed it sticks with 'pyvmomi==5.5.0'. Is there any specific reason? if I upgrade to (5.5.0.2014.1.1) I can work on pypy3-2.40 but if not..

 File "/home/pathcl/src/vsphere-python-restapi/methods.py", line 8, in <module>
    from pyVim import connect
  File "/home/pathcl/.pyenv/versions/pypy3-2.4.0/site-packages/pyVim/connect.py", line 331
    except Exception, e:
                   ^
SyntaxError: invalid syntax

its easy to fix. Just don't specify any version for pyvmomi on setup.py.

**Comment by pathcl** [comment]
Isnt python3 support planned? :)

**Comment by pathcl** [comment]
There's a weird inconsistency with print function. 
> Is it print("some") or print "some"? you could use from __future__ import print_function
> Why not use .format(object) instead of %s ?

**Comment by snobear** [comment]
I have not tested on python 3 and don't have any immediate plans to support it.  That said, I do see that pyvmomi supports 3.3/3.4, so we'd only need some basic tweaks to make it 3.x happy. 

Who wants to work on that :)?

**Comment by pathcl** [comment]
Well I'll fix it :)

**Comment by snobear** [comment]
@pathcl thats great thanks!

**Comment by Cory-Watson** [comment]
@snobear @pathcl , Any updates on this?

**Comment by pathcl** [comment]
Wow its been a while.. do you really need it? I could happily invest time

**Comment by snobear** [comment]
@Cory-Watson I'm pretty sure python 3 support was added in the latest release: https://github.com/snobear/ezmomi/releases/tag/6.5.0 which should be in pypi.

**Comment by TMadMac** [comment]
6.5.0 does not have the correction : print in setup.py do not have parenthesis.
Correction is on HEAD on master branch, but not realeased in any PIP package.

**Comment by im-n1** [comment]
I can confirm - master (this repo) is installable, PyPI version is not.

**Comment by snobear** [comment]
@TMadMac  @im-n1 OK I pushed the latest master to pypi. So this is now available as version 6.5.1.

https://pypi.org/project/ezmomi/6.5.1/
