### ISSUE TITLE
add a parameter to choose config file

### ISSUE THREAD

**Issue by andreagrax** [snobear/ezmomi#77]
I jump between various vcenters , a switch which permit to specify the correct datacenter would be great!

**Comment by snobear** [comment]
Hi @andreagrax - you can use the `EZMOMI_CONFIG` environment variable to specify a specify config to use.  You could prepend the ezmomi call with it to keep it a one-liner, e.g.:

```
EZMOMI_CONFIG=/path/to/config.yml ezmomi clone ...
```
