### ISSUE TITLE
Unable to assign an address

### ISSUE THREAD

**Issue by JoeDog** [snobear/ezmomi#89]
pg_obj.key is variable that undefined.  So I suspect this has something to do with this:
pg_obj = self.get_obj([vim.dvs.DistributedVirtualPortgroup], dvpg)  # noqa

# python2.7 haha clone --template Linux48G --hostname testy --cpus 2 >
Cloning Linux48G to new host testy with 4096MB RAM...
Traceback (most recent call last):
  File "haha", line 3, in <module>
    cli.cli()
  File "/home/jdfulmer/src/ezmomi/ezmomi/cli.py", line 18, in cli
    ez.clone()
  File "/home/jdfulmer/src/ezmomi/ezmomi/ezmomi.py", line 319, in clone
    print(pg_obj.key)
AttributeError: 'NoneType' object has no attribute 'key'

**Comment by JoeDog** [comment]
Don't worry about this. The problem was in vmware's software. It percent encoded a / in the name.

**Comment by snobear** [comment]
Thanks for the find as well as the update @JoeDog.
